import React, { useEffect, useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { ChevronDown, Clock3, LayoutDashboard, LogOut, ShoppingBag, ShieldAlert, Sparkles, User } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useCart } from '../../context/CartContext';
import quickbiteLogo from '../../assets/quickbite/quickbite-logo-main.png';

export const Navbar = () => {
  const { user, isAuthenticated, logout, isOwner, isAdmin } = useAuth();
  const { itemCount, setIsCartOpen } = useCart();
  const [open, setOpen] = useState(false);
  const ref = useRef(null); const navigate = useNavigate(); const location = useLocation();
  useEffect(() => { const close = (event) => !ref.current?.contains(event.target) && setOpen(false); document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  const linkClass = (path) => `rounded-xl px-3 py-2 text-sm font-bold transition ${location.pathname === path ? 'bg-orange-50 text-orange-700' : 'text-stone-600 hover:bg-stone-50 hover:text-stone-900'}`;
  return <header className="sticky top-0 z-40 border-b border-stone-200/80 bg-white/95 shadow-sm backdrop-blur-xl">
    {isAuthenticated && (isOwner || isAdmin) && <div className="bg-stone-900 px-4 py-1.5 text-xs font-medium text-stone-200"><div className="mx-auto flex max-w-[1560px] items-center justify-between gap-3"><span className="flex items-center gap-1.5"><Sparkles className="h-3.5 w-3.5 text-orange-300" /> Signed in as {user?.role?.replace('_', ' ')}</span><Link to={isAdmin ? '/admin' : '/owner'} className="font-bold text-orange-300 hover:text-orange-200">Open dashboard →</Link></div></div>}
    <div className="mx-auto flex h-[78px] max-w-[1560px] items-center justify-between gap-3 px-4 sm:px-6 lg:px-8">
      <div className="flex min-w-0 items-center"><Link to="/" aria-label="QuickBite home" className="block shrink-0 transition-transform hover:scale-[1.02]"><img src={quickbiteLogo} alt="QuickBite — Crave It. Get It. Love It." className="h-[54px] w-[190px] object-contain object-left sm:h-[67px] sm:w-[260px]" /></Link></div>
      <nav className="hidden items-center gap-1 md:flex"><Link to="/" className={linkClass('/')}>Home</Link><Link to="/restaurants" className={linkClass('/restaurants')}>Restaurants</Link>{isAuthenticated && <Link to="/orders" className={linkClass('/orders')}>My orders</Link>}{isOwner && <Link to="/owner" className="rounded-xl bg-amber-50 px-3 py-2 text-sm font-bold text-amber-800 hover:bg-amber-100">Partner portal</Link>}{isAdmin && <Link to="/admin" className="rounded-xl bg-violet-50 px-3 py-2 text-sm font-bold text-violet-800 hover:bg-violet-100">Admin</Link>}</nav>
      <div className="flex shrink-0 items-center gap-1.5 sm:gap-2"><button onClick={() => setIsCartOpen(true)} aria-label="Open cart" className="relative grid h-10 w-10 place-items-center rounded-xl bg-orange-50 text-orange-700 transition hover:bg-orange-100 active:scale-95"><ShoppingBag className="h-5 w-5" />{itemCount > 0 && <span className="absolute -right-1.5 -top-1.5 min-w-5 rounded-full bg-orange-600 px-1 py-0.5 text-[10px] font-black text-white">{itemCount}</span>}</button>{isAuthenticated ? <div className="relative" ref={ref}><button onClick={() => setOpen(!open)} className="flex items-center gap-1 rounded-xl border border-stone-200 p-1.5 text-stone-700 hover:bg-stone-50"><img src={user?.avatar || 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80'} alt="" className="h-7 w-7 rounded-lg object-cover" /><span className="hidden max-w-24 truncate text-xs font-bold sm:block">{user?.name}</span><ChevronDown className="hidden h-3.5 w-3.5 sm:block" /></button>{open && <div className="absolute right-0 mt-2 w-56 overflow-hidden rounded-2xl border border-stone-200 bg-white py-1 shadow-xl"><div className="border-b border-stone-100 px-4 py-3"><p className="truncate text-sm font-bold text-stone-900">{user?.name}</p><p className="truncate text-xs text-stone-500">{user?.email}</p></div><Link to="/profile" onClick={() => setOpen(false)} className="flex items-center gap-2 px-4 py-2.5 text-sm text-stone-700 hover:bg-orange-50"><User className="h-4 w-4" />Profile & addresses</Link><Link to="/orders" onClick={() => setOpen(false)} className="flex items-center gap-2 px-4 py-2.5 text-sm text-stone-700 hover:bg-orange-50"><Clock3 className="h-4 w-4" />Order history</Link><button onClick={() => { logout(); navigate('/login'); }} className="flex w-full items-center gap-2 border-t border-stone-100 px-4 py-2.5 text-left text-sm font-bold text-rose-600 hover:bg-rose-50"><LogOut className="h-4 w-4" />Log out</button></div>}</div> : <><Link to="/login" className="hidden rounded-xl px-3 py-2 text-sm font-bold text-stone-700 hover:bg-stone-50 sm:block">Sign in</Link><Link to="/register" className="rounded-xl bg-orange-600 px-3 py-2 text-sm font-bold text-white shadow-md shadow-orange-600/20 transition hover:bg-orange-700 active:scale-95 sm:px-4">Sign up</Link></>}</div>
    </div>
  </header>;
};
